#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"combine_files": "00_core.ipynb",
         "city_with_largets_population_from_df": "00_core.ipynb",
         "total_population_per_country_from_df": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/fastai/candidate_exercises_public/tree/master/"

def custom_doc_links(name): return None